import io
import json
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from bson.objectid import ObjectId
from database import get_db
from auth import get_current_user
from logger import app_logger

router = APIRouter(prefix="/api/reports", tags=["Reports"])


def generate_report_data(prediction: dict) -> dict:
    """Build structured report data from a prediction."""
    is_seizure = prediction["prediction"] == "Seizure"
    stats = prediction.get("signal_stats") or {}

    return {
        "report_title": "Epileptic Seizure Detection — AI Analysis Report",
        "generated_at": datetime.utcnow().isoformat(),
        "patient_file": {
            "filename": prediction["filename"],
            "file_type": prediction["file_type"],
            "upload_date": prediction["created_at"].isoformat() if isinstance(prediction["created_at"], datetime) else prediction["created_at"],
        },
        "ai_prediction": {
            "result": prediction["prediction"],
            "confidence": f"{prediction['confidence'] * 100:.1f}%",
            "confidence_value": prediction["confidence"],
        },
        "signal_analysis": {
            "num_data_points": stats.get("num_points", 178),
            "mean_amplitude": f"{stats.get('mean', 0):.2f} μV",
            "std_deviation": f"{stats.get('std', 0):.2f} μV",
            "min_amplitude": f"{stats.get('min', 0):.2f} μV",
            "max_amplitude": f"{stats.get('max', 0):.2f} μV",
            "signal_range": f"{stats.get('range', 0):.2f} μV",
        },
        "interpretation": {
            "pattern": (
                "The EEG signal shows patterns consistent with epileptic seizure activity, "
                "characterized by abnormal high-amplitude spikes and abnormal rhythmic patterns."
                if is_seizure
                else "The EEG signal shows normal brain electrical activity patterns "
                "within expected amplitude ranges. No seizure-like patterns detected."
            ),
            "severity": "Requires immediate medical attention" if is_seizure else "Normal",
        },
        "recommendations": [
            "This is an AI-assisted analysis and should NOT replace professional medical diagnosis.",
            "Please consult a qualified neurologist for a comprehensive evaluation.",
            *(
                [
                    "Recommend a follow-up clinical EEG monitoring session.",
                    "Consider anti-epileptic medication evaluation.",
                    "Avoid driving or operating heavy machinery until further evaluation.",
                    "Keep a seizure diary to track frequency and triggers.",
                ]
                if is_seizure
                else [
                    "Continue regular health checkups.",
                    "Maintain a healthy sleep schedule.",
                    "Report any unusual symptoms to your healthcare provider.",
                ]
            ),
        ],
        "disclaimer": (
            "DISCLAIMER: This report is generated by an AI system trained on the UCI Epileptic "
            "Seizure Recognition Dataset. It is intended for informational purposes only and "
            "should not be used as a substitute for professional medical advice, diagnosis, or treatment."
        ),
    }


def get_prediction_or_404(db, prediction_id: str, user_id: str) -> dict:
    try:
        obj_id = ObjectId(prediction_id)
    except:
        raise HTTPException(400, "Invalid prediction ID format")
        
    prediction = db.predictions.find_one({
        "_id": obj_id,
        "user_id": user_id
    })
    
    if not prediction:
        raise HTTPException(404, "Prediction not found")
        
    return prediction


@router.get("/{prediction_id}")
def get_report(
    prediction_id: str,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db),
):
    app_logger.info(f"User {current_user['id']} requested report for prediction {prediction_id}")
    prediction = get_prediction_or_404(db, prediction_id, current_user["id"])
    return generate_report_data(prediction)


@router.get("/{prediction_id}/download/json")
def download_json_report(
    prediction_id: str,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db),
):
    app_logger.info(f"User {current_user['id']} downloading JSON report for prediction {prediction_id}")
    prediction = get_prediction_or_404(db, prediction_id, current_user["id"])
    report = generate_report_data(prediction)
    content = json.dumps(report, indent=2)

    return StreamingResponse(
        io.BytesIO(content.encode()),
        media_type="application/json",
        headers={"Content-Disposition": f"attachment; filename=seizure_report_{prediction_id}.json"},
    )


@router.get("/{prediction_id}/download/pdf")
def download_pdf_report(
    prediction_id: str,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db),
):
    prediction = get_prediction_or_404(db, prediction_id, current_user["id"])
    report = generate_report_data(prediction)

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=50, bottomMargin=50)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#0077B6"))
        heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], textColor=colors.HexColor("#00B4D8"))

        elements = []

        elements.append(Paragraph(report["report_title"], title_style))
        elements.append(Spacer(1, 20))
        elements.append(Paragraph(f"Generated: {report['generated_at']}", styles["Normal"]))
        elements.append(Spacer(1, 20))

        # AI Prediction
        elements.append(Paragraph("AI Prediction Result", heading_style))
        pred = report["ai_prediction"]
        color = colors.red if pred["result"] == "Seizure" else colors.green
        elements.append(Paragraph(f"<b>Result:</b> <font color='{color}'>{pred['result']}</font>", styles["Normal"]))
        elements.append(Paragraph(f"<b>Confidence:</b> {pred['confidence']}", styles["Normal"]))
        elements.append(Spacer(1, 15))

        # Signal Analysis
        elements.append(Paragraph("Signal Analysis", heading_style))
        for key, val in report["signal_analysis"].items():
            elements.append(Paragraph(f"<b>{key.replace('_', ' ').title()}:</b> {val}", styles["Normal"]))
        elements.append(Spacer(1, 15))

        # Interpretation
        elements.append(Paragraph("Interpretation", heading_style))
        elements.append(Paragraph(report["interpretation"]["pattern"], styles["Normal"]))
        elements.append(Spacer(1, 15))

        # Recommendations
        elements.append(Paragraph("Recommendations", heading_style))
        for rec in report["recommendations"]:
            elements.append(Paragraph(f"• {rec}", styles["Normal"]))
        elements.append(Spacer(1, 15))

        # Disclaimer
        elements.append(Paragraph("Disclaimer", heading_style))
        elements.append(Paragraph(report["disclaimer"], styles["Italic"]))

        doc.build(elements)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=seizure_report_{prediction_id}.pdf"},
        )
    except ImportError:
        raise HTTPException(500, "reportlab not installed")


@router.get("/{prediction_id}/download/docx")
def download_docx_report(
    prediction_id: str,
    current_user: dict = Depends(get_current_user),
    db = Depends(get_db),
):
    prediction = get_prediction_or_404(db, prediction_id, current_user["id"])
    report = generate_report_data(prediction)

    try:
        from docx import Document
        from docx.shared import Pt, RGBColor

        doc = Document()
        doc.add_heading(report["report_title"], level=0)
        doc.add_paragraph(f"Generated: {report['generated_at']}")

        doc.add_heading("AI Prediction Result", level=1)
        pred = report["ai_prediction"]
        p = doc.add_paragraph()
        p.add_run(f"Result: {pred['result']}").bold = True
        doc.add_paragraph(f"Confidence: {pred['confidence']}")

        doc.add_heading("Signal Analysis", level=1)
        for key, val in report["signal_analysis"].items():
            doc.add_paragraph(f"{key.replace('_', ' ').title()}: {val}")

        doc.add_heading("Interpretation", level=1)
        doc.add_paragraph(report["interpretation"]["pattern"])

        doc.add_heading("Recommendations", level=1)
        for rec in report["recommendations"]:
            doc.add_paragraph(rec, style="List Bullet")

        doc.add_heading("Disclaimer", level=1)
        p = doc.add_paragraph()
        p.add_run(report["disclaimer"]).italic = True

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f"attachment; filename=seizure_report_{prediction_id}.docx"},
        )
    except ImportError:
        raise HTTPException(500, "python-docx not installed")
